export type VisualizationType = 
  | 'tcp' 
  | 'encryption' 
  | 'routing' 
  | 'dhcp' 
  | 'dns-resolution' 
  | 'firewall' 
  | 'vpn' 
  | 'load-balancing'
  | 'osi-model'
  | 'subnetting'
  | 'http-rest'
  | 'email'
  | 'attack-simulation'